source 'https://rubygems.org'

gem 'rails', '4.0.2'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'jbuilder', '~> 1.2'
group :doc do
  gem 'sdoc', require: false
end
gem 'debugger', group: [:development, :test]
gem 'mysql2'
gem 'devise'
gem 'acts_as_follower'
gem 'carrierwave'
gem 'acts_as_votable' 
gem 'kaminari'
gem 'mini_magick'
gem 'acts_as_commentable'
gem 'awesome_nested_fields'
gem 'rmagick'
gem 'public_activity'
gem 'omniauth'
gem 'omniauth-facebook' 
gem 'omniauth-google-oauth2'
gem 'omniauth-twitter'
gem 'websocket-rails'
# gem 'bootstrap-wysihtml5-rails'
gem 'gibbon'
gem 'bootsy'
gem 'acts-as-taggable-on', '~> 3.4'
gem 'roo'
