development:
  adapter: mysql2
  database: anak_pajak_development
  username: root
  password: 
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: anak_pajak_development
  username: root
  password: 
  host: localhost